# I NEED TO FIX THE WHITE BAR OVER THE NAVIGATOR ON HOME!!!!




application: bear-in-mind-cssi
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /
  script: main.app
  login: optional

- url: .*
  script: main.app
  login: required
#  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
