application: bear-in-mind
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: {{http://bear-in-mind-cssi.appspot.com/}}
  login: not required

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
